name: sound_byte
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  firebase_auth: ^0.15.1
  firebase_database: ^3.1.0
  cloud_firestore: ^0.12.11
  intl: ^0.16.0
  pointycastle: ^1.0.0-rc4
  encrypt: ^4.0.0
  password: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/