name: sound_byte
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_gherkin: 1.1.7+3
  firebase_auth: ^0.15.1
  firebase_database: ^3.1.0
  cloud_firestore: ^0.12.11
  intl: ^0.16.0
  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  fonts:
  - family: Laq
    fonts:
    - asset: fonts/Lacquer-Regular.ttf
  - family: Mont
    fonts:
    - asset: fonts/Montserrat-Black.ttf

  assets:
  - assets/waves.png
  - assets/background.png
